# Based on ubuntu
FROM ubuntu:18.04

# Copy from build directory
COPY person-detection-app /person-detection-app

# Define default command
ENTRYPOINT ["/person-detection-app"]

# Run the executable
CMD ["person-detection-app"]