apiVersion: devices.kubeedge.io/v1alpha2
kind: DeviceModel
metadata:
 name: buzzer-mqtt
 namespace: default
spec:
 properties:
  - name: power-status
    description: Indicates whether the buzzer is ON/OFF
    type:
      string:
        accessMode: ReadWrite
        defaultValue: 'OFF'
  - name: topic-mqtt
    description: topic for communication
    type:
      string:
        accessMode: ReadOnly
        defaultValue: 'esp32/buzzer'
